### ISSUE TITLE
MDB_MAP_FULL error

### ISSUE THREAD

**Issue by darshan-ghumare** [clibs/lmdb#1]
HI All,

I am getting following errors when running IOMeter for random writes with 4K block size,

qemu-system-x86_64: Write at offset 38834094 failed, error MDB_MAP_FULL: Environment mapsize limit reached

qemu-system-x86_64: Write at offset 38834094 failed, error MDB_MAP_FULL: Environment mapsize limit reached

qemu-system-x86_64: Write at offset 38834094 failed, error MDB_MAP_FULL: Environment mapsize limit reached

qemu-system-x86_64: Write at offset 38834094 failed, error MDB_MAP_FULL: Environment mapsize limit reached

qemu-system-x86_64: Write at offset 38834094 failed, error MDB_MAP_FULL: Environment mapsize limit reached

qemu-system-x86_64: Write at offset 38834094 failed, error MDB_MAP_FULL: Environment mapsize limit reached

qemu-system-x86_64: Write at offset 38834094 failed, error MDB_MAP_FULL: Environment mapsize limit reached

qemu-system-x86_64: Write at offset 38834094 failed, error MDB_MAP_FULL: Environment mapsize limit reached

qemu-system-x86_64: Write at offset 38834094 failed, error MDB_MAP_FULL: Environment mapsize limit reached

qemu-system-x86_64: Write at offset 4402334 failed, error MDB_MAP_FULL: Environment mapsize limit reached

qemu-system-x86_64: Write at offset 4402334 failed, error MDB_MAP_FULL: Environment mapsize limit reached

qemu-system-x86_64: Write at offset 4402334 failed, error MDB_MAP_FULL: Environment mapsize limit reached

Following is my setup,
    QEMU block driver which help me trap VM IOs. I am running IOMeter in VM.
    This driver has 2 threads, one for write and other for read.
    I have 16GB MMAP size, 
ret = mdb_env_create(&s->env);
if (ret != MDB_SUCCESS)
{
    error_setg_errno(errp, -EIO, "error: Can't create environment for LMDB, error %s\n", mdb_strer
    ret = -EIO;
    goto out;
}
ret = mdb_env_set_maxreaders(s->env, 1);
if (ret != MDB_SUCCESS)
{
    error_setg_errno(errp, -EIO, "error: Can't set max reader to 1, error %s\n", mdb_strerror(ret)
    ret = -EIO;
    goto out;
}
ret = mdb_env_set_mapsize(s->env, MMAP_SIZE);
if (ret != MDB_SUCCESS)
{
    error_setg_errno(errp, -EIO, "error: Can't set mmap size, error %s\n", mdb_strerror(ret));
    ret = -EIO;
    goto out;
}
ret = mdb_env_open(s->env, DBPath, MDB_FIXEDMAP | MDB_NOSYNC, 0664);
if (ret != MDB_SUCCESS)
{
    error_setg_errno(errp, -EIO, "error: Can't open db for given environment, error %s\n", mdb_strerror(ret));
    ret = -EIO;
    goto out;
}
ret = mdb_dbi_open(txn, NULL, 0, &s->dbi);
if (ret != MDB_SUCCESS)
{
    error_report("error: Can't open main db handle for given environment, error %s\n", mdb_strerror(ret));
    ret = -EIO;
    goto out;
}

```
   There is only one DBI shared between above thread (one DB, MAIN DB).
   Read thread has one transaction (which reset then renew before using). 
   Write starts new transaction for each IO.
```

My observation,
When DB size increases IOPS start dropping.
   Ex. For 4K random writes I am getting 9.3K when DB size is ~0GB, after couple of minutes when size reaches 16GB its drop down to 1K (and keeps dropping) at the same time I starts getting MDB_MAP_FULL error.

Please help.

Thanks,
Darshan

**Comment by willemt** [comment]
Hi Darshan

lmdb does not support automatic resizing. You are getting this error (ie. MDB_MAP_FULL) because you don't have a large enough map size (ie. your mdm_puts have gone past your database's capacity). I think you need to close the environment and database handle and re-open it with a larger mdb_env_set_mapsize.

Anyway, this repository is only a mirror of the real repository. It might be worth your time to ask on the mailing list: http://symas.com/mdb/#support

**Comment by darshan-ghumare** [comment]
Hi Willemt,

Thank you so much.
I have posted my question there too,  but the list is not responding.

I have following questions,
1.  For MDB_MAP_FULL error, reopening the DB with bigger MMAP size is the only solution
2.  As I mentioned IOPS drops when size of DB start increasing, is it expected behaviour.
3.  What is a point where DB size > MMAP size. Here, are we not limited by max process size as LMDB is a embedded DB.
4.  By default mdb_put() (mdb_put(txn, dbi, &key, &data, 0);) shall overwrite data if key exists, otherwise add new key-value pair, correct?

Thanks,
Darshan

**Comment by willemt** [comment]
1. Yes
2. Because the b-tree is getting larger it should naturally take longer to perform a put. How much should IOPS decrease? I'm afraid I can't tell you sorry. I believe it shouldn't be that much of a decrease in IOPS. From my experience you want to batch your puts, see https://github.com/willemt/bmon
3. I think the way lmdb is designed is mmap size = db size
4. Yes, by default it overwrites data or creates key-value pair. You need to pass the MDB_NOOVERWRITE flag to turn this behaviour off. See https://github.com/willemt/pearldb/blob/master/src/main.c#L440 and https://github.com/willemt/pearldb/blob/master/src/main.c#L198 for an example
